/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Bootcamp Treinos API
 * API para o bootcamp de treinos
 * OpenAPI spec version: 1.0.0
 */
import { customFetch } from "../fetch";
export type ListWorkoutPlansParams = {
  active?: ListWorkoutPlansActive;
};

export type ListWorkoutPlansActive =
  (typeof ListWorkoutPlansActive)[keyof typeof ListWorkoutPlansActive];

export const ListWorkoutPlansActive = {
  true: "true",
  false: "false",
} as const;

export type ListWorkoutPlans200ItemWorkoutDaysItemWeekDay =
  (typeof ListWorkoutPlans200ItemWorkoutDaysItemWeekDay)[keyof typeof ListWorkoutPlans200ItemWorkoutDaysItemWeekDay];

export const ListWorkoutPlans200ItemWorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type ListWorkoutPlans200ItemWorkoutDaysItemWorkoutExercisesItem = {
  id: string;
  name: string;
  order: number;
  sets: number;
  reps: number;
  restTimeInSeconds: number;
};

export type ListWorkoutPlans200ItemWorkoutDaysItem = {
  id: string;
  name: string;
  weekDay: ListWorkoutPlans200ItemWorkoutDaysItemWeekDay;
  isRest: boolean;
  estimatedDurationInSeconds: number;
  /** @nullable */
  coverImageUrl: string | null;
  workoutExercises: ListWorkoutPlans200ItemWorkoutDaysItemWorkoutExercisesItem[];
};

export type ListWorkoutPlans200Item = {
  id: string;
  name: string;
  isActive: boolean;
  workoutDays: ListWorkoutPlans200ItemWorkoutDaysItem[];
};

export type ListWorkoutPlans401 = {
  error: string;
  code: string;
};

export type ListWorkoutPlans500 = {
  error: string;
  code: string;
};

export type GetWorkplansId200WorkoutDaysItemWeekDay =
  (typeof GetWorkplansId200WorkoutDaysItemWeekDay)[keyof typeof GetWorkplansId200WorkoutDaysItemWeekDay];

export const GetWorkplansId200WorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type GetWorkplansId200WorkoutDaysItem = {
  id: string;
  weekDay: GetWorkplansId200WorkoutDaysItemWeekDay;
  name: string;
  isRest: boolean;
  /** @nullable */
  coverImageUrl?: string | null;
  estimatedDurationInSeconds: number;
  exercisesCount: number;
};

export type GetWorkplansId200 = {
  id: string;
  name: string;
  workoutDays: GetWorkplansId200WorkoutDaysItem[];
};

export type GetWorkplansId401 = {
  error: string;
  code: string;
};

export type GetWorkplansId404 = {
  error: string;
  code: string;
};

export type GetWorkplansId500 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlansBodyWorkoutDaysItemWeekDay =
  (typeof CreateWorkoutPlansBodyWorkoutDaysItemWeekDay)[keyof typeof CreateWorkoutPlansBodyWorkoutDaysItemWeekDay];

export const CreateWorkoutPlansBodyWorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type CreateWorkoutPlansBodyWorkoutDaysItemWorkoutExercisesItem = {
  /** @minimum 1 */
  order: number;
  /** @minLength 1 */
  name: string;
  /** @minimum 1 */
  sets: number;
  /** @minimum 1 */
  reps: number;
  /** @minimum 1 */
  restTimeInSeconds: number;
};

export type CreateWorkoutPlansBodyWorkoutDaysItem = {
  /** @minLength 1 */
  name: string;
  weekDay?: CreateWorkoutPlansBodyWorkoutDaysItemWeekDay;
  isRest?: boolean;
  /** @minimum 1 */
  estimatedDurationInSeconds: number;
  /** @nullable */
  coverImageUrl?: string | null;
  workoutExercises: CreateWorkoutPlansBodyWorkoutDaysItemWorkoutExercisesItem[];
};

export type CreateWorkoutPlansBody = {
  /** @minLength 1 */
  name: string;
  workoutDays: CreateWorkoutPlansBodyWorkoutDaysItem[];
};

export type CreateWorkoutPlans201WorkoutDaysItemWeekDay =
  (typeof CreateWorkoutPlans201WorkoutDaysItemWeekDay)[keyof typeof CreateWorkoutPlans201WorkoutDaysItemWeekDay];

export const CreateWorkoutPlans201WorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type CreateWorkoutPlans201WorkoutDaysItemWorkoutExercisesItem = {
  /** @minimum 1 */
  order: number;
  /** @minLength 1 */
  name: string;
  /** @minimum 1 */
  sets: number;
  /** @minimum 1 */
  reps: number;
  /** @minimum 1 */
  restTimeInSeconds: number;
};

export type CreateWorkoutPlans201WorkoutDaysItem = {
  /** @minLength 1 */
  name: string;
  weekDay: CreateWorkoutPlans201WorkoutDaysItemWeekDay;
  isRest: boolean;
  /** @minimum 1 */
  estimatedDurationInSeconds: number;
  /** @nullable */
  coverImageUrl?: string | null;
  workoutExercises: CreateWorkoutPlans201WorkoutDaysItemWorkoutExercisesItem[];
};

export type CreateWorkoutPlans201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @minLength 1 */
  name: string;
  workoutDays: CreateWorkoutPlans201WorkoutDaysItem[];
};

export type CreateWorkoutPlans400 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlans401 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlans404 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlans500 = {
  error: string;
  code: string;
};

export type GetWorkoutDays200WeekDay =
  (typeof GetWorkoutDays200WeekDay)[keyof typeof GetWorkoutDays200WeekDay];

export const GetWorkoutDays200WeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type GetWorkoutDays200ExercisesItem = {
  id: string;
  name: string;
  order: number;
  sets: number;
  reps: number;
  restTimeInSeconds: number;
  workoutDayId: string;
};

export type GetWorkoutDays200SessionsItem = {
  id: string;
  workoutDayId: string;
  startedAt?: string;
  completedAt?: string;
};

export type GetWorkoutDays200 = {
  id: string;
  name: string;
  isRest: boolean;
  /** @nullable */
  coverImageUrl?: string | null;
  estimatedDurationInSeconds: number;
  weekDay: GetWorkoutDays200WeekDay;
  exercises: GetWorkoutDays200ExercisesItem[];
  sessions: GetWorkoutDays200SessionsItem[];
};

export type GetWorkoutDays401 = {
  error: string;
  code: string;
};

export type GetWorkoutDays404 = {
  error: string;
  code: string;
};

export type GetWorkoutDays500 = {
  error: string;
  code: string;
};

export type StartWorkoutSession201 = {
  userWorkoutSessionId: string;
};

export type StartWorkoutSession401 = {
  error: string;
  code: string;
};

export type StartWorkoutSession404 = {
  error: string;
  code: string;
};

export type StartWorkoutSession409 = {
  error: string;
  code: string;
};

export type StartWorkoutSession422 = {
  error: string;
  code: string;
};

export type StartWorkoutSession500 = {
  error: string;
  code: string;
};

export type UpdateWorkoutSessionBody = {
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  completedAt: string;
};

export type UpdateWorkoutSession200 = {
  id: string;
  completedAt: string;
  startedAt: string;
};

export type UpdateWorkoutSession401 = {
  error: string;
  code: string;
};

export type UpdateWorkoutSession404 = {
  error: string;
  code: string;
};

export type UpdateWorkoutSession500 = {
  error: string;
  code: string;
};

export type GetHomePageData200TodayWorkoutDayWeekDay =
  (typeof GetHomePageData200TodayWorkoutDayWeekDay)[keyof typeof GetHomePageData200TodayWorkoutDayWeekDay];

export const GetHomePageData200TodayWorkoutDayWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type GetHomePageData200TodayWorkoutDay = {
  workoutPlanId: string;
  id: string;
  name: string;
  isRest: boolean;
  weekDay: GetHomePageData200TodayWorkoutDayWeekDay;
  estimatedDurationInSeconds: number;
  /** @nullable */
  coverImageUrl?: string | null;
  exercisesCount: number;
};

export type GetHomePageData200ConsistencyByDay = {
  [key: string]: {
    workoutDayCompleted: boolean;
    workoutDayStarted: boolean;
  };
};

export type GetHomePageData200 = {
  activeWorkoutPlanId: string;
  todayWorkoutDay: GetHomePageData200TodayWorkoutDay;
  workoutStreak: number;
  consistencyByDay: GetHomePageData200ConsistencyByDay;
};

export type GetHomePageData401 = {
  error: string;
  code: string;
};

export type GetHomePageData404 = {
  error: string;
  code: string;
};

export type GetHomePageData500 = {
  error: string;
  code: string;
};

export type GetUserWorkoutStatsParams = {
  /**
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
   */
  from: string;
  /**
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
   */
  to: string;
};

export type GetUserWorkoutStats200ConsistencyByDay = {
  [key: string]: {
    workoutDayCompleted: boolean;
    workoutDayStarted: boolean;
  };
};

export type GetUserWorkoutStats200 = {
  workoutStreak: number;
  consistencyByDay: GetUserWorkoutStats200ConsistencyByDay;
  completedWorkoutsCount: number;
  conclusionRate: number;
  totalTimeInSeconds: number;
};

export type GetUserWorkoutStats401 = {
  error: string;
  code: string;
};

export type GetUserWorkoutStats404 = {
  error: string;
  code: string;
};

export type GetUserWorkoutStats500 = {
  error: string;
  code: string;
};

/**
 * @nullable
 */
export type GetCurrentUserTrainData200 = {
  userId: string;
  userName: string;
  weightInGrams: number;
  heightInCentimeters: number;
  age: number;
  bodyFatPercentage: number;
} | null;

export type GetCurrentUserTrainData401 = {
  error: string;
  code: string;
};

export type GetCurrentUserTrainData500 = {
  error: string;
  code: string;
};

export type UpsertCurrentUserTrainDataBody = {
  weightInGrams: number;
  heightInCentimeters: number;
  age: number;
  bodyFatPercentage: number;
};

export type UpsertCurrentUserTrainData200 = {
  userId: string;
  weightInGrams: number;
  heightInCentimeters: number;
  age: number;
  bodyFatPercentage: number;
};

export type UpsertCurrentUserTrainData401 = {
  error: string;
  code: string;
};

export type UpsertCurrentUserTrainData500 = {
  error: string;
  code: string;
};

export type PostAiBody = {
  messages: unknown[];
};

export type PostAi401 = {
  error: string;
  code: string;
};

export type Get200 = {
  message: string;
};

/**
 * @summary List workout plans
 */
export type listWorkoutPlansResponse200 = {
  data: ListWorkoutPlans200Item[];
  status: 200;
};

export type listWorkoutPlansResponse401 = {
  data: ListWorkoutPlans401;
  status: 401;
};

export type listWorkoutPlansResponse500 = {
  data: ListWorkoutPlans500;
  status: 500;
};

export type listWorkoutPlansResponseSuccess = listWorkoutPlansResponse200 & {
  headers: Headers;
};
export type listWorkoutPlansResponseError = (
  | listWorkoutPlansResponse401
  | listWorkoutPlansResponse500
) & {
  headers: Headers;
};

export type listWorkoutPlansResponse =
  | listWorkoutPlansResponseSuccess
  | listWorkoutPlansResponseError;

export const getListWorkoutPlansUrl = (params?: ListWorkoutPlansParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/workout-plans/workout-plans?${stringifiedParams}`
    : `/workout-plans/workout-plans`;
};

export const listWorkoutPlans = async (
  params?: ListWorkoutPlansParams,
  options?: RequestInit,
): Promise<listWorkoutPlansResponse> => {
  return customFetch<listWorkoutPlansResponse>(getListWorkoutPlansUrl(params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Get Workout Plan by ID
 */
export type getWorkplansIdResponse200 = {
  data: GetWorkplansId200;
  status: 200;
};

export type getWorkplansIdResponse401 = {
  data: GetWorkplansId401;
  status: 401;
};

export type getWorkplansIdResponse404 = {
  data: GetWorkplansId404;
  status: 404;
};

export type getWorkplansIdResponse500 = {
  data: GetWorkplansId500;
  status: 500;
};

export type getWorkplansIdResponseSuccess = getWorkplansIdResponse200 & {
  headers: Headers;
};
export type getWorkplansIdResponseError = (
  | getWorkplansIdResponse401
  | getWorkplansIdResponse404
  | getWorkplansIdResponse500
) & {
  headers: Headers;
};

export type getWorkplansIdResponse =
  | getWorkplansIdResponseSuccess
  | getWorkplansIdResponseError;

export const getGetWorkplansIdUrl = (id: string) => {
  return `/workout-plans/${id}`;
};

export const getWorkplansId = async (
  id: string,
  options?: RequestInit,
): Promise<getWorkplansIdResponse> => {
  return customFetch<getWorkplansIdResponse>(getGetWorkplansIdUrl(id), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Create Workout Plan
 */
export type createWorkoutPlansResponse201 = {
  data: CreateWorkoutPlans201;
  status: 201;
};

export type createWorkoutPlansResponse400 = {
  data: CreateWorkoutPlans400;
  status: 400;
};

export type createWorkoutPlansResponse401 = {
  data: CreateWorkoutPlans401;
  status: 401;
};

export type createWorkoutPlansResponse404 = {
  data: CreateWorkoutPlans404;
  status: 404;
};

export type createWorkoutPlansResponse500 = {
  data: CreateWorkoutPlans500;
  status: 500;
};

export type createWorkoutPlansResponseSuccess =
  createWorkoutPlansResponse201 & {
    headers: Headers;
  };
export type createWorkoutPlansResponseError = (
  | createWorkoutPlansResponse400
  | createWorkoutPlansResponse401
  | createWorkoutPlansResponse404
  | createWorkoutPlansResponse500
) & {
  headers: Headers;
};

export type createWorkoutPlansResponse =
  | createWorkoutPlansResponseSuccess
  | createWorkoutPlansResponseError;

export const getCreateWorkoutPlansUrl = () => {
  return `/workout-plans/`;
};

export const createWorkoutPlans = async (
  createWorkoutPlansBody: CreateWorkoutPlansBody,
  options?: RequestInit,
): Promise<createWorkoutPlansResponse> => {
  return customFetch<createWorkoutPlansResponse>(getCreateWorkoutPlansUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createWorkoutPlansBody),
  });
};

/**
 * @summary Get Workout Day by ID
 */
export type getWorkoutDaysResponse200 = {
  data: GetWorkoutDays200;
  status: 200;
};

export type getWorkoutDaysResponse401 = {
  data: GetWorkoutDays401;
  status: 401;
};

export type getWorkoutDaysResponse404 = {
  data: GetWorkoutDays404;
  status: 404;
};

export type getWorkoutDaysResponse500 = {
  data: GetWorkoutDays500;
  status: 500;
};

export type getWorkoutDaysResponseSuccess = getWorkoutDaysResponse200 & {
  headers: Headers;
};
export type getWorkoutDaysResponseError = (
  | getWorkoutDaysResponse401
  | getWorkoutDaysResponse404
  | getWorkoutDaysResponse500
) & {
  headers: Headers;
};

export type getWorkoutDaysResponse =
  | getWorkoutDaysResponseSuccess
  | getWorkoutDaysResponseError;

export const getGetWorkoutDaysUrl = (
  workoutPlanId: string,
  workoutDayId: string,
) => {
  return `/workout-plans/${workoutPlanId}/days/${workoutDayId}`;
};

export const getWorkoutDays = async (
  workoutPlanId: string,
  workoutDayId: string,
  options?: RequestInit,
): Promise<getWorkoutDaysResponse> => {
  return customFetch<getWorkoutDaysResponse>(
    getGetWorkoutDaysUrl(workoutPlanId, workoutDayId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Start Workout Session
 */
export type startWorkoutSessionResponse201 = {
  data: StartWorkoutSession201;
  status: 201;
};

export type startWorkoutSessionResponse401 = {
  data: StartWorkoutSession401;
  status: 401;
};

export type startWorkoutSessionResponse404 = {
  data: StartWorkoutSession404;
  status: 404;
};

export type startWorkoutSessionResponse409 = {
  data: StartWorkoutSession409;
  status: 409;
};

export type startWorkoutSessionResponse422 = {
  data: StartWorkoutSession422;
  status: 422;
};

export type startWorkoutSessionResponse500 = {
  data: StartWorkoutSession500;
  status: 500;
};

export type startWorkoutSessionResponseSuccess =
  startWorkoutSessionResponse201 & {
    headers: Headers;
  };
export type startWorkoutSessionResponseError = (
  | startWorkoutSessionResponse401
  | startWorkoutSessionResponse404
  | startWorkoutSessionResponse409
  | startWorkoutSessionResponse422
  | startWorkoutSessionResponse500
) & {
  headers: Headers;
};

export type startWorkoutSessionResponse =
  | startWorkoutSessionResponseSuccess
  | startWorkoutSessionResponseError;

export const getStartWorkoutSessionUrl = (
  workoutPlanId: string,
  workoutDayId: string,
) => {
  return `/workout-plans/${workoutPlanId}/days/${workoutDayId}/sessions`;
};

export const startWorkoutSession = async (
  workoutPlanId: string,
  workoutDayId: string,
  options?: RequestInit,
): Promise<startWorkoutSessionResponse> => {
  return customFetch<startWorkoutSessionResponse>(
    getStartWorkoutSessionUrl(workoutPlanId, workoutDayId),
    {
      ...options,
      method: "POST",
    },
  );
};

/**
 * @summary Update Workout Session
 */
export type updateWorkoutSessionResponse200 = {
  data: UpdateWorkoutSession200;
  status: 200;
};

export type updateWorkoutSessionResponse401 = {
  data: UpdateWorkoutSession401;
  status: 401;
};

export type updateWorkoutSessionResponse404 = {
  data: UpdateWorkoutSession404;
  status: 404;
};

export type updateWorkoutSessionResponse500 = {
  data: UpdateWorkoutSession500;
  status: 500;
};

export type updateWorkoutSessionResponseSuccess =
  updateWorkoutSessionResponse200 & {
    headers: Headers;
  };
export type updateWorkoutSessionResponseError = (
  | updateWorkoutSessionResponse401
  | updateWorkoutSessionResponse404
  | updateWorkoutSessionResponse500
) & {
  headers: Headers;
};

export type updateWorkoutSessionResponse =
  | updateWorkoutSessionResponseSuccess
  | updateWorkoutSessionResponseError;

export const getUpdateWorkoutSessionUrl = (
  workoutPlanId: string,
  workoutDayId: string,
  workoutSessionId: string,
) => {
  return `/workout-plans/${workoutPlanId}/days/${workoutDayId}/sessions/${workoutSessionId}`;
};

export const updateWorkoutSession = async (
  workoutPlanId: string,
  workoutDayId: string,
  workoutSessionId: string,
  updateWorkoutSessionBody: UpdateWorkoutSessionBody,
  options?: RequestInit,
): Promise<updateWorkoutSessionResponse> => {
  return customFetch<updateWorkoutSessionResponse>(
    getUpdateWorkoutSessionUrl(workoutPlanId, workoutDayId, workoutSessionId),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(updateWorkoutSessionBody),
    },
  );
};

/**
 * @summary Get home page data
 */
export type getHomePageDataResponse200 = {
  data: GetHomePageData200;
  status: 200;
};

export type getHomePageDataResponse401 = {
  data: GetHomePageData401;
  status: 401;
};

export type getHomePageDataResponse404 = {
  data: GetHomePageData404;
  status: 404;
};

export type getHomePageDataResponse500 = {
  data: GetHomePageData500;
  status: 500;
};

export type getHomePageDataResponseSuccess = getHomePageDataResponse200 & {
  headers: Headers;
};
export type getHomePageDataResponseError = (
  | getHomePageDataResponse401
  | getHomePageDataResponse404
  | getHomePageDataResponse500
) & {
  headers: Headers;
};

export type getHomePageDataResponse =
  | getHomePageDataResponseSuccess
  | getHomePageDataResponseError;

export const getGetHomePageDataUrl = (date: string) => {
  return `/home/${date}`;
};

export const getHomePageData = async (
  date: string,
  options?: RequestInit,
): Promise<getHomePageDataResponse> => {
  return customFetch<getHomePageDataResponse>(getGetHomePageDataUrl(date), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Get user workout statistics
 */
export type getUserWorkoutStatsResponse200 = {
  data: GetUserWorkoutStats200;
  status: 200;
};

export type getUserWorkoutStatsResponse401 = {
  data: GetUserWorkoutStats401;
  status: 401;
};

export type getUserWorkoutStatsResponse404 = {
  data: GetUserWorkoutStats404;
  status: 404;
};

export type getUserWorkoutStatsResponse500 = {
  data: GetUserWorkoutStats500;
  status: 500;
};

export type getUserWorkoutStatsResponseSuccess =
  getUserWorkoutStatsResponse200 & {
    headers: Headers;
  };
export type getUserWorkoutStatsResponseError = (
  | getUserWorkoutStatsResponse401
  | getUserWorkoutStatsResponse404
  | getUserWorkoutStatsResponse500
) & {
  headers: Headers;
};

export type getUserWorkoutStatsResponse =
  | getUserWorkoutStatsResponseSuccess
  | getUserWorkoutStatsResponseError;

export const getGetUserWorkoutStatsUrl = (
  params: GetUserWorkoutStatsParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/stats/?${stringifiedParams}`
    : `/stats/`;
};

export const getUserWorkoutStats = async (
  params: GetUserWorkoutStatsParams,
  options?: RequestInit,
): Promise<getUserWorkoutStatsResponse> => {
  return customFetch<getUserWorkoutStatsResponse>(
    getGetUserWorkoutStatsUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Get current user train data
 */
export type getCurrentUserTrainDataResponse200 = {
  data: GetCurrentUserTrainData200;
  status: 200;
};

export type getCurrentUserTrainDataResponse401 = {
  data: GetCurrentUserTrainData401;
  status: 401;
};

export type getCurrentUserTrainDataResponse500 = {
  data: GetCurrentUserTrainData500;
  status: 500;
};

export type getCurrentUserTrainDataResponseSuccess =
  getCurrentUserTrainDataResponse200 & {
    headers: Headers;
  };
export type getCurrentUserTrainDataResponseError = (
  | getCurrentUserTrainDataResponse401
  | getCurrentUserTrainDataResponse500
) & {
  headers: Headers;
};

export type getCurrentUserTrainDataResponse =
  | getCurrentUserTrainDataResponseSuccess
  | getCurrentUserTrainDataResponseError;

export const getGetCurrentUserTrainDataUrl = () => {
  return `/me/`;
};

export const getCurrentUserTrainData = async (
  options?: RequestInit,
): Promise<getCurrentUserTrainDataResponse> => {
  return customFetch<getCurrentUserTrainDataResponse>(
    getGetCurrentUserTrainDataUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Upsert current user train data
 */
export type upsertCurrentUserTrainDataResponse200 = {
  data: UpsertCurrentUserTrainData200;
  status: 200;
};

export type upsertCurrentUserTrainDataResponse401 = {
  data: UpsertCurrentUserTrainData401;
  status: 401;
};

export type upsertCurrentUserTrainDataResponse500 = {
  data: UpsertCurrentUserTrainData500;
  status: 500;
};

export type upsertCurrentUserTrainDataResponseSuccess =
  upsertCurrentUserTrainDataResponse200 & {
    headers: Headers;
  };
export type upsertCurrentUserTrainDataResponseError = (
  | upsertCurrentUserTrainDataResponse401
  | upsertCurrentUserTrainDataResponse500
) & {
  headers: Headers;
};

export type upsertCurrentUserTrainDataResponse =
  | upsertCurrentUserTrainDataResponseSuccess
  | upsertCurrentUserTrainDataResponseError;

export const getUpsertCurrentUserTrainDataUrl = () => {
  return `/me/me`;
};

export const upsertCurrentUserTrainData = async (
  upsertCurrentUserTrainDataBody: UpsertCurrentUserTrainDataBody,
  options?: RequestInit,
): Promise<upsertCurrentUserTrainDataResponse> => {
  return customFetch<upsertCurrentUserTrainDataResponse>(
    getUpsertCurrentUserTrainDataUrl(),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(upsertCurrentUserTrainDataBody),
    },
  );
};

/**
 * @summary Chat with the AI personal trainer
 */
export type postAiResponse200 = {
  data: unknown;
  status: 200;
};

export type postAiResponse401 = {
  data: PostAi401;
  status: 401;
};

export type postAiResponseSuccess = postAiResponse200 & {
  headers: Headers;
};
export type postAiResponseError = postAiResponse401 & {
  headers: Headers;
};

export type postAiResponse = postAiResponseSuccess | postAiResponseError;

export const getPostAiUrl = () => {
  return `/ai/`;
};

export const postAi = async (
  postAiBody: PostAiBody,
  options?: RequestInit,
): Promise<postAiResponse> => {
  return customFetch<postAiResponse>(getPostAiUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(postAiBody),
  });
};

export type getResponse200 = {
  data: Get200;
  status: 200;
};

export type getResponseSuccess = getResponse200 & {
  headers: Headers;
};
export type getResponse = getResponseSuccess;

export const getGetUrl = () => {
  return `/`;
};

export const get = async (options?: RequestInit): Promise<getResponse> => {
  return customFetch<getResponse>(getGetUrl(), {
    ...options,
    method: "GET",
  });
};
